project_id = "ysvmjwgeedpyegbqpema"

[functions.send-contact-email]
verify_jwt = false

[functions.get-checkin-data]
verify_jwt = false

[functions.get-round-data]
verify_jwt = false

[functions.submit-match-results]
verify_jwt = false
